---
baseurl: ""

# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Knife-Zero
tagline:          'Local Mode via SSH.'
description:      'Run chef-client at remote node with chef-zero(local-mode) via HTTP over SSH port fowarding. '
url:              https://knife-zero.github.io

gems:
  - jekyll-sitemap

author:
  name:           'SAWANOBORI Yukihiko'
  url:            https://github.com/sawanoboly

paginate:         null

# Custom vars
version:          1.8.x

github:
  repo:  https://github.com/higanworks/knife-zero

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor

